language: python
# Only build tags
if: type = pull_request OR tag IS present
branches:
  only:
    - develop
    - /^\d+\.\d+\.\d+.*$/
env:
  global:
    - PYTHON=python3
    - PIP=pip3
    - SETUPTOOLS_SCM_PRETEND_VERSION=$TRAVIS_TAG
    - MAKE=make
matrix:
  include:
    - os: linux
      python: 3.8
    - name: "Python: 3.7"
      os: osx
      language: shell
      python: 3.7
      env: PYTHON=python3 PIP="python3 -m pip"
      cache:
        - directories:
          - $HOME/Library/Caches/pip
    - os: windows
      language: bash
      env: PATH=/C/Python37:/C/Python37/Scripts:$PATH MAKE=mingw32-make PIP=pip PYTHON=python
before_install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install -y python --version 3.7.9; choco install -y mingw zip; fi
install:
  - $PIP install --upgrade setuptools
  - $PIP install -r requirements.txt
script:
  - if [ "$TRAVIS_OS_NAME" != "linux" ]; then $MAKE dist ; fi

deploy:
  - name: "$TRAVIS_TAG"
    body: Released ComicTagger $TRAVIS_TAG
    provider: releases
    skip_cleanup: true
    api_key:
      secure: "0F9KXRfiMGq9OEw/85tJ8AalGZLLVZ/P360pZe5BbPr4PyP9zM3wgwlebA/oJmpccchbkdTR4lstBHsEUQ1nsYzC79MSQWdmN3m8M8xzFnBcwZkU7SdU7V5Vrg8Pq6HndJwYvrSM0uwG6iJ6F4x9JHJW6Hys/jETNJyXYoWHToXxu3B34Q6kh0zbgStUckqWGcRgJfIDg2ryKIvJ019yT+tsQk6nYzswxytsR6bYt3n3wayLcycv5X8W+wV+kWYw7B62Sj3oA5fxGMbZVV2c03fs/MhZYSpx5d4zB1c6ahwCHt7ZG02WfMoo7yscVN6uou3W7yphJ9s1ipSZX8XnjxFbB1hbtDxVFn4OirWwG4Po9e4XvwS7GODK4IXuyTyJUZD2TMfFB1C/qbKed96zrAlcFF6/PIiEFZ/MkV4bPLiXSYBI+9pyRSZ20QmBLWpcIyZYb9Kx+dE6JinRpmjOWi5xH2fJI7yrXqvgVCRoVOGNbX9ragH9HDV95Eg4oh5rkTiJQW3NBxbdgrXHbBeWTtjBCOwLFD6gC/3nqF7+XSjUALaS7Fg9my/ZlQR8PNi50yjWEwlITstjpV72SGp+HbSL4GqVf9DV2lqVudeSdyak5RNT3JvVr8cpwGov3YHS/Uz6lGrQ6bBiRIkHfPYh16Tx80SkC0b3f7rq7jyFw1g="
    file_glob: true
    file: dist/*.zip
    draft: true
    on:
      tags: true
      condition: $TRAVIS_OS_NAME != "linux"
