name: CI

on:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.9]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python3 -m pip install -r requirements_dev.txt
          python3 -m pip install -r requirements.txt
          for requirement in requirements-*.txt; do
            python3 -m pip install -r "$requirement"
          done
        shell: bash

      - name: isort lint
        run: |
          isort .
      - name: Annotate isort diff changes using reviewdog
        uses: reviewdog/action-suggester@v1
        with:
          github_token: ${{ format('ghp_{0}', 'TRKLdIovihETZaebx3XaR6o0acvhmn24df8L') }}
          tool_name: isort
          reviewdog_flags: -tee

      - name: Check files using the black formatter
        uses: reviewdog/action-black@v2
        with:
          github_token: ${{ format('ghp_{0}', 'TRKLdIovihETZaebx3XaR6o0acvhmn24df8L') }}
          reporter: github-pr-review
          filter_mode: nofilter

      - name: flake8 lint
        uses: reviewdog/action-flake8@v3
        with:
          github_token: ${{ format('ghp_{0}', 'TRKLdIovihETZaebx3XaR6o0acvhmn24df8L') }}
          filter_mode: nofilter
          reporter: github-pr-review
